Fixes for the frontend
c2c-project/prytaneum-client pull request #136
Opened 2021-10-30 22:29 UTC by claynaut

### 1. Please briefly explain what it is you coded
Coded fixes for the frontend, mainly from the issues I listed under #128. Fixes involve resolving alignment issues, proper form validation, and miscellaneous UI content like how labels were displayed.

### 2. Please briefly explain your approach (new components added? modified? removed?)
Fixed alignment issues by reorganizing grid items. Implemented form validation (for organizations and event settings) through Yup by creating a validation schema passed through useFormik. Modified how event details were displayed for start/end date and time by splitting the key string. Modified the settings menu to have a title prop which can be modified for the respective page (e.g. user settings or event settings).

### 3. Any packages added/updated/removed
N/A

### (Optional) 4. Any feature recommendations/insights/questions/comments/etc.?

2021-12-07 02:49 UTC, DevelopmentByDavid requested changes
Looks good.  Thank you for all the work!  This is my first quick review and then I'll be checking it out locally for the next pass.  

Also, where I said to use `useMemo` it's not completely necessary.  The main goal is to abstract out that logic into a function where you can add more checks without the jsx markup starting to look cluttered -- `useMemo` on top of that is a very minor optimization.

2021-12-07 02:49 UTC, DevelopmentByDavid commented on app/client/src/components/SettingsMenu/SettingsMenu.tsx
>  }
This file should be reverted to the previous state it was in. I think there was some sort of merge mishap (Kelton and I knew a few months ago, but neither of us has gotten to it).  I'll probably revert this file and then merge it into dev and then you will merge it into your branch so that everything works correctly.

2021-12-07 02:49 UTC, DevelopmentByDavid commented on app/client/src/features/events/EventForm.tsx
> +    description: Yup.string().required('Please enter a description'),
The description should be optional, but you should probably ask Kevin.

2021-12-07 02:49 UTC, DevelopmentByDavid commented on app/client/src/features/events/EventSettings/EventDetails.tsx
> +                    <Typography variant='overline'>
I think this will be unnecessary with reverting `SettingsMenu` -- not 100% sure.

2021-12-07 02:49 UTC, DevelopmentByDavid commented on app/client/src/features/events/EventSettings/EventSettings.tsx
> +                        title='Event Settings'
Unfortunately, I think this will also be fixed with `SettingsMenu` being reverted.

2021-12-07 02:49 UTC, DevelopmentByDavid commented on app/client/src/features/events/Moderation/CreateModerator.tsx
> +import { useSnack } from '@local/features/core';
Nitpicky: This should be in the second block of imports.  External imports in first block, local ones in second block.

2021-12-07 02:49 UTC, DevelopmentByDavid commented on app/client/src/features/events/Moderation/ModeratorEventSettings.tsx
> +                            <ListItemText primary={firstName ? `${firstName} ${lastName}` : 'Pending Registration...'} secondary={email} />
For thoroughness, this should probably be generated with a `useMemo`.  There's a few cases here: If `firstName` is defined but `lastName` is not, we don't want to display "David Undefined".  Displaying "David" alone is probably okay.  So we should check whether or not lastName exists too.  Could do something like `const displayName = useMemo(() => ...);`

2021-12-07 02:49 UTC, DevelopmentByDavid commented on app/client/src/features/events/Speakers/SpeakerForm.tsx
> +    pictureUrl: Yup.string().required('Please enter a picture URL'),
Please use yup's [url validator](https://github.com/jquense/yup#stringurlmessage-string--function-schema)

2021-12-07 02:49 UTC, DevelopmentByDavid commented on app/client/src/features/events/Videos/VideoForm.tsx
> +    url: Yup.string().required('Please enter a video URL'),
Same URL schema comment from previous file

2021-12-07 02:49 UTC, DevelopmentByDavid commented on app/client/src/features/organizations/OrgMemberList.tsx
> +                                <ListItemText primary={node.firstName ? `${node.firstName} ${node.lastName}` : 'Pending Registration...'} />
Same comment as before about using `useMemo` here.

2021-12-07 04:56 UTC, kadey001 commented on app/client/src/components/SettingsMenu/SettingsMenu.tsx
>  }
I have already fixed this, it should be up to date in dev if you do a merge into your working branch. Just be sure the settings are in the flat design and not the compact one.

2022-12-07 05:28 UTC, kadey001 approved these changes, later dismissed

2022-12-07 05:54 UTC, kadey001 approved these changes

2022-12-07 05:54 UTC, merged