Joseph259
c2c-project/prytaneum-client pull request #98
Opened 2021-03-18 01:22 UTC by JosephPark259

Not sure if this is a permanent solution but I just use a shallow copy (save on temp variable) and set the state as so.

Let me know what you think

2021-03-19 03:09 UTC, JosephPark259 commented
@DevelopmentByDavid Updated!

2021-03-20 02:38 UTC, DevelopmentByDavid requested changes
Looks good!  Two minor comments.

2021-03-20 02:38 UTC, DevelopmentByDavid commented on src/contexts/Townhall.tsx
> +type Dispatch = React.Dispatch<SetStateAction<Townhall | undefined >>  | null;
I'm not sure that inside the SetStateAction we should have `Townhall | undefined` I think it should just be Townhall and undefined is outside of the generic like the null.

2021-03-20 02:38 UTC, DevelopmentByDavid commented on src/domains/Townhall/TownhallSettings/TownhallSettings.tsx
> +            setTownhall({...townhall, settings:state});
This should probably use `setTownhall(prev => ({ ...townhall, settings: state}));`. It's a bit hard to explain over text, but I could do a call with you to explain.

2021-03-21 02:30 UTC, DevelopmentByDavid commented on src/contexts/Townhall.tsx
> +type Dispatch = React.Dispatch<SetStateAction<Townhall | undefined >>  | null;
I'm wrong!

2021-03-21 03:12 UTC, merged